service: lambda-layer-sharp
frameworkVersion: ">=1.34.0 <2.0.0"
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
layers:
  sharp:
    path: layer
    compatibleRuntimes:
      - nodejs8.10
resources:
  Outputs:
    SharpLayerExport:
      Value:
        Ref: SharpLambdaLayer
      Export:
        Name: SharpLambdaLayer
